---
- name: install XFS packages
  apt: pkg=xfsprogs update_cache=yes
  sudo: yes
- name: gather EC2 facts
  action: ec2_facts
- name: create EC2 volume
  ec2_vol: device_name=/dev/sd{{device_letter}} volume_size={{volume_size}} region={{ansible_ec2_placement_region}} zone={{ansible_ec2_placement_availability_zone}} instance={{ansible_ec2_instance_id}} aws_access_key={{aws_key}} aws_secret_key={{aws_secret}}
- name: format volume
  filesystem: fstype=xfs dev=/dev/xvd{{device_letter}}
  sudo: yes
- name: mount volume
  mount: fstype=xfs name={{ebs_path}} src=/dev/xvd{{device_letter}} state=mounted
  sudo: yes
