---
- name: write /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts
- name: set hostname
  hostname: name={{hostname}}
- name: upgrade packages
  apt: upgrade=yes
- name: install base packages
  apt: pkg={{item}} update_cache=yes
  with_items:
      - build-essential
      - git
      - mercurial
- name: install extra packages
  apt: pkg={{item}}
  with_items: extra_packages
