---
- name: add postgres key
  apt_key: state=present id=ACCC4CF8 url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
- name: add postgres repository
  apt_repository: state=present update_cache=yes repo="deb http://apt.postgresql.org/pub/repos/apt/ saucy-pgdg main"
- name: install postgres and postgis
  apt: pkg={{item}} update_cache=yes
  with_items:
      - postgresql-9.3
      - postgresql-9.3-postgis-2.1
      - postgresql-server-dev-9.3
- name: install psycopg2 package
  apt: pkg=python-psycopg2 update_cache=yes
- name: create postgres user
  postgresql_user: name={{dbuser}} password={{dbpassword}} role_attr_flags=SUPERUSER state=present
  sudo_user: postgres
- name: create postgres database
  postgresql_db: name={{dbname}}
  sudo_user: postgres
  notify:
    - load postgis
